baseURL : "https://prajkt-yeole.github.io/hugo-documentation/"
languageCode : "en-us"
title : "Xenon"
disableKinds:
  - taxonomy
  - taxonomyTerm
enableEmoji: true
markup:
  goldmark:
    renderer:
      unsafe: true
params :
  author : "Prajkt Yeole"
  siteDescription : "HUGO based Documentation template. Write your product's documentation or create a knowledge base and deploy on your server."
  keywords: "hugo , docs"
  color_theme: ""
